"""Utility helpers — safe code execution and data serialization."""
import contextlib
import io
import json
import math
from typing import Any, Dict, Optional, Tuple

import numpy as np
import pandas as pd
import structlog

log = structlog.get_logger(__name__)


# ── Safe Code Execution ───────────────────────────────────────


def safe_exec(
    code: str,
    dataframes: Dict[str, pd.DataFrame],
) -> Tuple[Optional[Any], Optional[str], Optional[str]]:
    """
    Execute Pandas code in a restricted namespace.

    Parameters
    ----------
    code : str
        Python code generated by the LLM. Should assign its answer to ``result``.
    dataframes : dict
        Mapping of variable name → DataFrame (e.g., {"df": df0}).

    Returns
    -------
    (result, stdout, error)
        - result  : value of the ``result`` variable after execution, or None
        - stdout  : captured stdout text, or None
        - error   : exception message if execution failed, or None
    """
    # Restricted builtins — no file I/O, no arbitrary imports
    restricted_builtins: dict = {
        "__builtins__": {
            "print": print,
            "len": len, "range": range, "enumerate": enumerate,
            "list": list, "dict": dict, "set": set, "tuple": tuple,
            "sum": sum, "min": min, "max": max, "abs": abs, "round": round,
            "sorted": sorted, "reversed": reversed,
            "zip": zip, "map": map, "filter": filter,
            "str": str, "int": int, "float": float, "bool": bool,
            "type": type, "isinstance": isinstance, "hasattr": hasattr,
            "getattr": getattr,
            "any": any, "all": all,
            "None": None, "True": True, "False": False,
            "ValueError": ValueError, "KeyError": KeyError,
            "TypeError": TypeError, "IndexError": IndexError,
            "Exception": Exception,
        }
    }
    import scipy.stats as stats
    # Provide pandas, numpy, math, scipy.stats — the typical toolkit for LLM-generated code
    namespace: dict = {
        **restricted_builtins,
        "pd": pd,
        "np": np,
        "math": math,
        "stats": stats,
        "scipy": type('obj', (object,), {'stats': stats}),
    }
    namespace.update(dataframes)

    stdout_buf = io.StringIO()
    import textwrap
    import re
    code = textwrap.dedent(code).strip()
    # Strip out any import statements generated by the LLM 
    # since we already provide pd, np, math and __import__ is disabled for safety.
    code = re.sub(r'^(?:from\s+[\w.]+\s+)?import\s+.*$', '', code, flags=re.MULTILINE)
    try:
        with contextlib.redirect_stdout(stdout_buf):
            exec(compile(code, "<llm_generated>", "exec"), namespace)  # noqa: S102
        result = namespace.get("result", None)
        stdout_text = stdout_buf.getvalue() or None
        return result, stdout_text, None
    except Exception as exc:
        log.warning("safe_exec.error", error=str(exc))
        return None, stdout_buf.getvalue() or None, str(exc)


# ── Data Serialization ────────────────────────────────────────


def serialize_result(value: Any) -> Any:
    """
    Convert a code execution result into a JSON-serialisable Python object.
    Handles DataFrames, Series, numpy scalars, and Python primitives.
    """
    if isinstance(value, pd.DataFrame):
        # Replace NaN/Inf with None for JSON safety
        clean = value.copy()
        for col in clean.select_dtypes(include="number").columns:
            clean[col] = clean[col].apply(
                lambda x: None if isinstance(x, float) and (math.isnan(x) or math.isinf(x)) else x
            )
        return clean.where(pd.notna(clean), None).to_dict(orient="records")

    if isinstance(value, pd.Series):
        # Reset index so we get {index_col: ..., value_col: ...} records
        df = value.reset_index()
        df.columns = [str(c) for c in df.columns]
        return serialize_result(df)

    if isinstance(value, (np.integer,)):
        return int(value)

    if isinstance(value, (np.floating,)):
        v = float(value)
        return None if (math.isnan(v) or math.isinf(v)) else v

    if isinstance(value, np.ndarray):
        return value.tolist()

    if isinstance(value, (list, tuple)):
        return [serialize_result(item) for item in value]

    if isinstance(value, dict):
        return {str(k): serialize_result(v) for k, v in value.items()}

    # Scalar numbers — guard against NaN/Inf
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        return None

    return value


def df_to_json_safe(df: pd.DataFrame) -> str:
    """Serialize a DataFrame to a JSON string, replacing NaN/Inf with null."""
    records = serialize_result(df)
    return json.dumps(records, default=str)


def result_to_chart_data(value: Any) -> list:
    """
    Convert a code execution result to a list-of-dicts suitable for Recharts.
    - DataFrame / list-of-dicts  → returned as-is
    - Series                     → converted to {index, value} records
    - Scalar                     → [{"value": scalar}]
    - None                       → []
    """
    serialized = serialize_result(value)
    if isinstance(serialized, list):
        return serialized
    if serialized is not None:
        return [{"value": serialized}]
    return []
